server:
  port: 6268

eureka:
  instance:
    hostname: discovery
    port: 9090
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    healthcheck:
      enabled: true   # 开启